"""Derive the wheel's closed asset bundle from canonical source files."""
import hashlib
import json
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py


SOURCE_ASSETS = (
    "fixtures/assay_map.json",
    "frontend/index.html",
    "operational-model/artifacts/model-receipt.json",
    "operational-model/artifacts/model.json",
    "operational-model/example-input.json",
)


class BuildPortableAssets(build_py):
    def run(self):
        super().run()
        source_root = Path(__file__).parent.resolve()
        package = Path(self.build_lib) / "oac_clinical_resources"
        bundle = package / "assets"
        entries = []
        for relative in SOURCE_ASSETS:
            source = source_root / relative
            if source.is_symlink() or not source.is_file():
                raise RuntimeError(f"canonical portable asset is not a regular file: {relative}")
            source.resolve().relative_to(source_root)
            payload = source.read_bytes()
            destination = "clinical-gateway/" + relative
            target = bundle / destination
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
            entries.append({"path": destination, "size_bytes": len(payload),
                            "sha256": hashlib.sha256(payload).hexdigest()})
        manifest = {"schema": "szl-oac/portable-workspace-assets/v1",
                    "package_version": self.distribution.get_version(), "files": entries}
        encoded = (json.dumps(manifest, sort_keys=True, indent=2) + "\n").encode("utf-8")
        (bundle / "manifest.json").write_bytes(encoded)
        expected = {entry["path"] for entry in entries} | {"manifest.json"}
        observed = {p.relative_to(bundle).as_posix() for p in bundle.rglob("*") if p.is_file()}
        if observed != expected:
            raise RuntimeError("portable asset build directory contains undeclared files; use a fresh build directory")
        (package / "_asset_integrity.py").write_text(
            '# Generated by the trusted build from canonical source assets.\n'
            f'MANIFEST_SHA256 = "{hashlib.sha256(encoded).hexdigest()}"\n', encoding="utf-8")


setup(cmdclass={"build_py": BuildPortableAssets})
