"""Regenerate the registered v2 data splits byte-exact and compare them with the manifests.

SYNTHETIC.  The registered splits (v2/data/*.jsonl and v2/data/sealed/*.jsonl, 48 MB) and the five
AM-4 known-good train splits are not committed under ops-health/.  This tool rebuilds each one
with the frozen generator (v2/research/generator.py, through v2/research/make_data.py and
v2/research/stage2.py), writes it into a temporary directory, re-reads the written bytes and
compares their sha256 and size with the committed record:

* every split in v2/data/MANIFEST.json ("splits": sha256, bytes);
* every retrain in v2/results/known_good/INDEX.json ("retrains.kN.train": sha256, bytes, rows);
* every contender in v2/results/contenders/INDEX.json that records a train_sha256 over a prefix
  of the registered train split ("train_rows" rows).

It hashes bytes only.  No row is parsed, scored or summarized, and nothing is printed about any
row's content; the sealed splits are generated, hashed and deleted, never evaluated.  The
protocol's single opening of the sealed splits happened in the research repository and is not
repeated here (see ops-health/README.md).

Usage (from the szl-forge repository root):
    python -B ops-health/tools/regenerate_data.py --verify-against ops-health/v2/data/MANIFEST.json

Options:
    --out-dir DIR        keep the regenerated files in DIR (must not exist) instead of a temp dir
    --materialize        after a successful check, also write the files at their registered paths
                         under ops-health/ (exclusive create; never overwrites).  Needed only to run
                         ``python -m v2.research.make_data --verify``, which hashes the on-disk bytes.
    --compare-on-disk    also compare with files already present at their registered paths
                         (in the research repository they are committed)
    --report PATH        write the JSON report to PATH as well as stdout

Exit 0 when every regenerated file matches its record, 1 otherwise.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path

OPS_HEALTH = Path(__file__).resolve().parents[1]


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _write_exclusive(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("xb") as handle:
        handle.write(data)


def _prefix_lines(data: bytes, rows: int) -> bytes:
    lines = data.split(b"\n")
    if len(lines) <= rows:
        raise ValueError(f"split has fewer than {rows} rows")
    return b"\n".join(lines[:rows]) + b"\n"


def regenerate(root: Path, manifest_path: Path, out_dir: Path, *, compare_on_disk: bool) -> dict:
    sys.path.insert(0, str(root))
    from v2.research import generator, make_data, registry, stage2  # noqa: E402  (frozen code)

    if registry.ROOT.resolve() != root.resolve():
        raise SystemExit(f"imported v2 from {registry.ROOT}, expected {root}; refusing")
    manifest_bytes = manifest_path.read_bytes()
    manifest = json.loads(manifest_bytes.decode("utf-8"))
    problems: list[str] = []
    generator_sha = _sha256(registry.GENERATOR_PATH.read_bytes())
    if manifest["generator_sha256"] != generator_sha:
        problems.append("generator.py sha256 differs from MANIFEST generator_sha256")
    if manifest["preregistration_sha256"] != _sha256(registry.PREREG_PATH.read_bytes()):
        problems.append("PREREGISTRATION.md sha256 differs from MANIFEST")
    if set(manifest["splits"]) != set(registry.SPLIT_TABLE):
        problems.append("MANIFEST splits differ from the registered split table")

    checked: dict[str, dict] = {}
    regenerated: dict[str, bytes] = {}

    def check(key: str, rel: str, data: bytes, expected_sha: str, expected_bytes: int | None) -> None:
        target = out_dir / rel
        _write_exclusive(target, data)
        on_out = target.read_bytes()  # hash the bytes as written
        digest = _sha256(on_out)
        entry = {"path": rel, "sha256": digest, "bytes": len(on_out),
                 "matches": digest == expected_sha and (expected_bytes is None or len(on_out) == expected_bytes)}
        if not entry["matches"]:
            problems.append(f"{key}: regenerated sha256/bytes differ from the record")
        if compare_on_disk:
            disk = root / rel
            if disk.is_file():
                entry["committed_bytes_identical"] = disk.read_bytes() == on_out
                if not entry["committed_bytes_identical"]:
                    problems.append(f"{key}: regenerated bytes differ from {rel} on disk")
            else:
                entry["committed_bytes_identical"] = None
        checked[key] = entry

    for name, *_rest in registry.SPLITS:
        record = manifest["splits"][name]
        data = make_data._split_bytes(name)  # generator.generate_rows(name, rows, regime)
        regenerated[name] = data
        check(f"split:{name}", record["path"], data, record["sha256"], record["bytes"])

    kg_index_path = root / "v2" / "results" / "known_good" / "INDEX.json"
    if kg_index_path.is_file():
        index = json.loads(kg_index_path.read_text(encoding="utf-8"))
        for key, info in sorted(index["retrains"].items()):
            k = int(info["k"])
            if info["seed_material"] != stage2.known_good_seed_material(k):
                problems.append(f"known_good {key}: seed material differs from stage2's")
            rows = stage2.known_good_rows(k, int(info["train"]["rows"]))
            data = generator.jsonl_bytes(rows)
            check(f"known_good:{key}", info["train"]["path"], data, info["train"]["sha256"],
                  info["train"]["bytes"])

    contenders_path = root / "v2" / "results" / "contenders" / "INDEX.json"
    if contenders_path.is_file():
        contenders = json.loads(contenders_path.read_text(encoding="utf-8"))
        for key, info in sorted(contenders["contenders"].items()):
            if "train_sha256" not in info:
                continue
            data = _prefix_lines(regenerated["train"], int(info["train_rows"]))
            digest = _sha256(data)
            ok = digest == info["train_sha256"]
            checked[f"contender_train_prefix:{key}"] = {
                "rows": int(info["train_rows"]), "of": "split:train", "sha256": digest, "matches": ok}
            if not ok:
                problems.append(f"contender {key}: train prefix sha256 differs from INDEX.json")

    return {
        "schema": "szl-oac/ops-health-regenerate-data/v1",
        "synthetic": True,
        "ok": not problems,
        "problems": problems,
        "manifest": {"path": manifest_path.resolve().relative_to(root.resolve()).as_posix(),
                     "sha256": _sha256(manifest_bytes)},
        "generator_sha256": generator_sha,
        "checked": checked,
        "note": "bytes hashed only; no row parsed, scored or summarized",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--verify-against", required=True, type=Path,
                        help="the data manifest, e.g. ops-health/v2/data/MANIFEST.json")
    parser.add_argument("--root", type=Path, default=OPS_HEALTH,
                        help="the directory holding v2/ (default: this tool's ops-health/)")
    parser.add_argument("--out-dir", type=Path)
    parser.add_argument("--materialize", action="store_true")
    parser.add_argument("--compare-on-disk", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    manifest_path = args.verify_against.resolve()
    if manifest_path != (root / "v2" / "data" / "MANIFEST.json").resolve():
        print(f"--verify-against must be {root / 'v2' / 'data' / 'MANIFEST.json'}", file=sys.stderr)
        return 2
    if args.out_dir is not None:
        if args.out_dir.exists():
            print(f"--out-dir {args.out_dir} exists; refusing", file=sys.stderr)
            return 2
        out_dir, cleanup = args.out_dir.resolve(), False
    else:
        out_dir, cleanup = Path(tempfile.mkdtemp(prefix="ops-health-regen-")), True
    try:
        report = regenerate(root, manifest_path, out_dir, compare_on_disk=args.compare_on_disk)
        if report["ok"] and args.materialize:
            written = []
            for entry in report["checked"].values():
                if "path" not in entry:
                    continue
                target = root / entry["path"]
                if target.exists():
                    if target.read_bytes() != (out_dir / entry["path"]).read_bytes():
                        report["ok"] = False
                        report["problems"].append(f"{entry['path']} exists with other bytes")
                    continue
                _write_exclusive(target, (out_dir / entry["path"]).read_bytes())
                written.append(entry["path"])
            report["materialized"] = written
    finally:
        if cleanup:
            shutil.rmtree(out_dir, ignore_errors=True)
    text = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.report is not None:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_bytes(text.encode("utf-8"))
    sys.stdout.write(text)
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
