#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# (c) 2026 SZL Holdings. Generated by szl-payload 4.0.0 for candidate willay-candidate-20261001.
"""Shared helpers for this frontier candidate.

Stdlib only at import time; torch/transformers/peft are imported inside the functions
that need them so contract tests and CI run without a GPU or model account.
Doctrine: fail closed, strings not floats in receipts, text-only tokenizer path,
no promotion authority anywhere in this folder.
"""
import datetime as dt
import hashlib
import json
import os
import platform
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = Path(os.environ.get("SZL_CANDIDATE_OUT") or (HERE / "out"))
REFUSAL_MARKERS = ("REFUSE", "ABSTAIN", "INSUFFICIENT_EVIDENCE", "OUT_OF_POLICY", "CANNOT COMPLY")
LOCK_PACKAGES = ("torch", "transformers", "peft", "trl", "datasets", "accelerate", "bitsandbytes",
                 "safetensors", "huggingface_hub", "unsloth", "unsloth_zoo", "numpy")


def now_utc():
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_dir(directory, suffix=".safetensors"):
    files = sorted(p for p in Path(directory).glob("*" + suffix))
    if not files:
        raise SystemExit(f"[receipt] no *{suffix} files in {directory}")
    h = hashlib.sha256()
    for p in files:
        h.update(p.name.encode("utf-8"))
        h.update(bytes.fromhex(sha256_file(p)))
    return h.hexdigest()


def stringify_floats(value):
    """Receipts carry strings and integers only; floats never canonicalize identically across runtimes."""
    if isinstance(value, bool) or value is None or isinstance(value, (int, str)):
        return value
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, dict):
        return {k: stringify_floats(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [stringify_floats(v) for v in value]
    return str(value)


def load_candidate():
    return read_json(HERE / "candidate.json")


def save_candidate(cand):
    write_json(HERE / "candidate.json", cand)


def load_gates(cand=None):
    cand = cand or load_candidate()
    text = (HERE / cand.get("gates_file", "gates.json")).read_text(encoding="utf-8")
    digest = sha256_text(text)
    if digest != cand.get("gates_sha256"):
        raise SystemExit(f"GATES_TAMPERED: gates.json sha256 {digest} != candidate.gates_sha256 "
                         f"{cand.get('gates_sha256')}. Thresholds are frozen before results are seen.")
    return json.loads(text)


def read_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except ValueError as e:
                raise SystemExit(f"[curriculum] {path}:{n} is not valid JSON: {e}")
    return rows


def _msg(role, content):
    return {"role": role, "content": content if isinstance(content, str) else canonical(content)}


def normalize_record(rec):
    """Accepts chat (`messages`), prompt/completion, instruction(+input)/output, input/output, text/label.
    Returns {"messages", "expected", "family_key", "example_id", "split", "evidence_handles"} or raises ValueError."""
    if not isinstance(rec, dict):
        raise ValueError("record is not an object")
    msgs = None
    if isinstance(rec.get("messages"), list) and rec["messages"]:
        msgs = [_msg(m.get("role", "user"), m.get("content", "")) for m in rec["messages"] if isinstance(m, dict)]
    elif "prompt" in rec and ("completion" in rec or "response" in rec):
        msgs = [_msg("user", rec["prompt"]), _msg("assistant", rec.get("completion", rec.get("response")))]
    elif "instruction" in rec and "output" in rec:
        user = rec["instruction"] + ("\n\n" + rec["input"] if rec.get("input") else "")
        msgs = [_msg("user", user), _msg("assistant", rec["output"])]
    elif "input" in rec and "output" in rec:
        msgs = [_msg("user", rec["input"]), _msg("assistant", rec["output"])]
    elif "text" in rec and "label" in rec:
        msgs = [_msg("user", rec["text"]), _msg("assistant", canonical({"label": rec["label"]}))]
    if not msgs or msgs[-1]["role"] != "assistant" or not any(m["role"] == "user" for m in msgs):
        raise ValueError("record has no user turn followed by an assistant turn")
    if isinstance(rec.get("system"), str) and msgs[0]["role"] != "system":
        msgs.insert(0, _msg("system", rec["system"]))
    expected = rec.get("expected") if isinstance(rec.get("expected"), dict) else {}
    parsed = parse_json_output(msgs[-1]["content"])
    if isinstance(parsed, dict):
        expected = {**parsed, **expected}
    for key in ("label", "abstain", "decision", "refuse"):
        if key in rec and key not in expected:
            expected[key] = rec[key]
    expected["_text"] = msgs[-1]["content"]
    handles = rec.get("evidence_handles")
    if handles is None:
        for m in msgs:
            j = parse_json_output(m["content"]) if m["role"] != "assistant" else None
            if isinstance(j, dict) and isinstance(j.get("evidence_handles"), list):
                handles = j["evidence_handles"]
    body = canonical([m for m in msgs])
    return {"messages": msgs, "expected": expected,
            "family_key": str(rec.get("family_key") or rec.get("source") or rec.get("family") or "") or None,
            "example_id": str(rec.get("example_id") or rec.get("id") or sha256_text(body)[:16]),
            "split": str(rec.get("split") or "").lower() or None,
            "evidence_handles": [str(h) for h in handles] if isinstance(handles, list) else None}


def parse_json_output(text):
    """Return the first balanced JSON object in text, or None."""
    if not isinstance(text, str):
        return None
    start = text.find("{")
    while start != -1:
        depth, in_str, esc = 0, False, False
        for i in range(start, len(text)):
            ch = text[i]
            if in_str:
                if esc:
                    esc = False
                elif ch == "\\":
                    esc = True
                elif ch == '"':
                    in_str = False
                continue
            if ch == '"':
                in_str = True
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    try:
                        return json.loads(text[start:i + 1])
                    except ValueError:
                        break
        start = text.find("{", start + 1)
    return None


def is_refusal(text):
    up = (text or "").upper()
    return any(m in up for m in REFUSAL_MARKERS)


def expected_abstain(expected):
    if expected.get("abstain") is True or expected.get("refuse") is True:
        return True
    if str(expected.get("decision", "")).upper() in ("ABSTAIN", "REFUSE", "REFUSAL"):
        return True
    return is_refusal(expected.get("_text", "")) and not isinstance(parse_json_output(expected.get("_text", "")), dict)


def produced_abstain(text, parsed):
    if isinstance(parsed, dict):
        if parsed.get("abstain") is True or str(parsed.get("decision", "")).upper() in ("ABSTAIN", "REFUSE", "REFUSAL"):
            return True
    return is_refusal(text)


# ----------------------------------------------------------------------------- curriculum binding
def curriculum_files(cand):
    """Resolve bound curriculum files -> {split: Path}. Exits 3 when unbound. Verifies digests."""
    td = cand.get("training_data") or {}
    if td.get("binding_status") not in ("BOUND_LOCAL", "BOUND_IN_REPO"):
        write_json(OUT / "curriculum_report.json", {"verdict": "UNBOUND", "generated_utc": now_utc(),
                   "instruction": "Bind a curriculum in candidate.json: training_data.binding_status=BOUND_LOCAL "
                                  "or BOUND_IN_REPO with files{split:{path,sha256}}. Admitted rows must be "
                                  "project-authored or rights-documented. No training runs while UNBOUND.",
                   "candidates_observed": td.get("candidates_observed", [])})
        raise SystemExit(3)
    out = {}
    for split, spec in (td.get("files") or {}).items():
        p = Path(spec["path"])
        if not p.is_absolute():
            p = HERE / p
        if not p.is_file():
            raise SystemExit(f"[curriculum] bound file missing: {p}")
        digest = sha256_file(p)
        if spec.get("sha256") and spec["sha256"] != digest:
            raise SystemExit(f"[curriculum] {p} sha256 {digest} != bound {spec['sha256']}; refusing a drifted corpus")
        out[split] = p
    if not out:
        raise SystemExit("[curriculum] binding has no files")
    return out


def load_splits(cand):
    """Load bound files, honour per-record split tags, derive deterministic splits when only one file is bound."""
    files = curriculum_files(cand)
    rows, bad, excluded = {"train": [], "dev": [], "test": [], "adversarial": []}, [], 0
    aliases = {"eval": "dev", "validation": "dev", "val": "dev", "heldout": "test", "held_out": "test",
               "final": "test", "refusals": "train", "abstain": "train", "red_team": "adversarial"}
    for file_split, path in files.items():
        for i, raw in enumerate(read_jsonl(path)):
            try:
                rec = normalize_record(raw)
            except ValueError as e:
                bad.append({"file": str(path), "line": i + 1, "error": str(e)})
                continue
            split = rec["split"] or file_split
            split = aliases.get(split, split)
            if split in ("quarantine", "excluded", "rejected"):
                excluded += 1
                continue
            if split == "all":
                split = None
            if split not in rows:
                bucket = int(sha256_text(rec["family_key"] or rec["example_id"])[:8], 16) % 100
                split = "train" if bucket < 80 else "dev" if bucket < 90 else "test"
            rec["split"] = split
            rows[split].append(rec)
    return rows, bad, excluded


# ----------------------------------------------------------------------------- leakage gate
def shingles(text, n=5):
    toks = re.findall(r"[a-z0-9]+", text.lower())
    if len(toks) < n:
        return {" ".join(toks)} if toks else set()
    return {" ".join(toks[i:i + n]) for i in range(len(toks) - n + 1)}


def template_signature(text):
    t = re.sub(r'"[^"]*"', '"S"', text)
    t = re.sub(r"\d+(\.\d+)?", "0", t.lower())
    return re.sub(r"\s+", " ", t).strip()


def _prompt_text(rec):
    return "\n".join(m["content"] for m in rec["messages"] if m["role"] != "assistant")


def leakage_report(train, held, thresholds):
    """Exact-hash, 5-gram Jaccard, family-key isolation and template-leak checks between train and held rows."""
    thr_j = float(thresholds.get("max_jaccard5", 0.8))
    train_hash = {sha256_text(_prompt_text(r)) for r in train}
    exact = [r["example_id"] for r in held if sha256_text(_prompt_text(r)) in train_hash]
    train_sh = [(r["example_id"], shingles(_prompt_text(r))) for r in train]
    flagged, max_j = [], 0.0
    for r in held:
        sh = shingles(_prompt_text(r))
        best, best_id = 0.0, None
        for tid, tsh in train_sh:
            if not sh or not tsh:
                continue
            j = len(sh & tsh) / len(sh | tsh)
            if j > best:
                best, best_id = j, tid
        max_j = max(max_j, best)
        if best >= thr_j:
            flagged.append({"held": r["example_id"], "train": best_id, "jaccard5": repr(round(best, 4))})
    train_fam = {r["family_key"] for r in train if r["family_key"]}
    fam_overlap = sorted({r["family_key"] for r in held if r["family_key"] and r["family_key"] in train_fam})
    train_tpl = {template_signature(_prompt_text(r)) for r in train}
    tpl_overlap = sum(1 for r in held if template_signature(_prompt_text(r)) in train_tpl)
    checks = {"exact_duplicates": {"value": len(exact), "pass": len(exact) == 0},
              "near_duplicates_jaccard5": {"value": len(flagged), "max_jaccard5": repr(round(max_j, 4)),
                                           "threshold": repr(thr_j), "pass": len(flagged) == 0},
              "family_key_isolation": {"value": len(fam_overlap), "pass": len(fam_overlap) == 0},
              "template_leak": {"value": tpl_overlap, "blocking": bool(thresholds.get("template_leak_blocks", False)),
                                "status": "PASS" if tpl_overlap == 0 else "FAIL" if thresholds.get("template_leak_blocks", False) else "WARN",
                                "pass": tpl_overlap == 0 or not bool(thresholds.get("template_leak_blocks", False))}}
    return {"kind": "szl.frontier-leakage-receipt/v1", "generated_utc": now_utc(), "train_rows": len(train),
            "held_rows": len(held), "checks": checks, "exact_duplicate_ids": exact[:50], "flagged_pairs": flagged[:50],
            "family_overlap": fam_overlap[:50], "verdict": "PASS" if all(c["pass"] for c in checks.values()) else "FAIL"}


# ----------------------------------------------------------------------------- runtime + model helpers
def text_only_encode(tokenizer, messages, add_generation_prompt):
    """Render with the chat template and tokenize the STRING with the tokenizer.
    Never hand a positional string to an AutoProcessor: Qwen3-VL-class processors read it as an image argument."""
    kwargs = {"tokenize": False, "add_generation_prompt": add_generation_prompt}
    if "enable_thinking" in str(getattr(tokenizer, "chat_template", "") or ""):
        kwargs["enable_thinking"] = False  # Qwen3-family templates: structured outputs, no thinking block
    text = tokenizer.apply_chat_template(messages, **kwargs)
    ids = tokenizer(text, add_special_tokens=False)["input_ids"]
    return text, list(ids)


def load_tokenizer(repo_id, revision=None):
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(repo_id, revision=revision)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    return tok


def installed_versions():
    import importlib
    out = {}
    for name in LOCK_PACKAGES:
        try:
            mod = importlib.import_module(name)
            out[name] = str(getattr(mod, "__version__", "present"))
        except Exception:
            out[name] = None
    out["python"] = platform.python_version()
    return out


def gpu_snapshot():
    snap = {"cuda_available": False, "device": None, "total_gib": None, "free_gib": None}
    try:
        import torch
        snap["torch_cuda"] = torch.version.cuda
        if torch.cuda.is_available():
            free, total = torch.cuda.mem_get_info()
            snap.update(cuda_available=True, device=torch.cuda.get_device_name(0),
                        total_gib=repr(round(total / 2**30, 2)), free_gib=repr(round(free / 2**30, 2)))
    except Exception as e:
        snap["error"] = f"{type(e).__name__}: {e}"
    return snap


def load_base_model(cand, for_training, allow_cpu=False):
    """Load the pinned base as a causal LM. Prefers Unsloth when importable; falls back to transformers+peft.
    Returns (model, tokenizer, backend)."""
    base = cand["actual_training_base"]
    recipe = cand["training_recipe"]
    repo, rev = base["repo_id"], base.get("revision")
    import torch
    device_cuda = torch.cuda.is_available()
    if not device_cuda and not allow_cpu:
        raise SystemExit("[model] CUDA unavailable; pass --allow-cpu only for tiny contract smoke runs")
    use_4bit = bool(base.get("load_in_4bit", True)) and device_cuda
    try:
        from unsloth import FastLanguageModel
        model, tok = FastLanguageModel.from_pretrained(model_name=repo, revision=rev, max_seq_length=recipe["max_length"],
                                                       load_in_4bit=use_4bit, dtype=None)
        if for_training:
            model = FastLanguageModel.get_peft_model(
                model, r=recipe["lora_r"], lora_alpha=recipe["lora_alpha"], lora_dropout=recipe["lora_dropout"],
                target_modules=recipe["target_modules"], bias="none", use_gradient_checkpointing="unsloth",
                random_state=recipe["seed"])
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token
        return model, tok, "unsloth"
    except Exception as e:  # guarded fallback: the plain stack is slower but version-stable
        print(f"[model] unsloth path unavailable ({type(e).__name__}: {str(e)[:160]}); using transformers+peft")
    import transformers
    kwargs = {"revision": rev}
    if use_4bit:
        try:
            from transformers import BitsAndBytesConfig
            kwargs["quantization_config"] = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                                                               bnb_4bit_compute_dtype=torch.bfloat16,
                                                               bnb_4bit_use_double_quant=True)
            kwargs["device_map"] = {"": 0}
        except Exception as e:
            print(f"[model] bitsandbytes unavailable ({type(e).__name__}); loading bf16 full precision")
            kwargs["dtype"] = torch.bfloat16
            kwargs["device_map"] = {"": 0}
    elif device_cuda:
        kwargs["dtype"] = torch.bfloat16
        kwargs["device_map"] = {"": 0}
    else:
        kwargs["dtype"] = torch.float32
    model, errors = None, []
    for loader in ("AutoModelForCausalLM", "AutoModelForImageTextToText", "AutoModelForVision2Seq"):
        cls = getattr(transformers, loader, None)
        if cls is None:
            continue
        for kw in (kwargs, {**{k: v for k, v in kwargs.items() if k != "dtype"}, "torch_dtype": kwargs.get("dtype")}):
            try:
                model = cls.from_pretrained(repo, **kw)
                break
            except (TypeError, ValueError, KeyError) as e:
                errors.append(f"{loader}: {type(e).__name__}: {str(e)[:120]}")
        if model is not None:
            break
    if model is None:
        raise SystemExit("[model] could not load base with any causal/multimodal loader: " + " | ".join(errors[-4:]))
    tok = load_tokenizer(repo, rev)
    if for_training:
        from peft import LoraConfig, get_peft_model
        if use_4bit:
            try:
                from peft import prepare_model_for_kbit_training
                model = prepare_model_for_kbit_training(model)
            except Exception:
                pass
        model = get_peft_model(model, LoraConfig(r=recipe["lora_r"], lora_alpha=recipe["lora_alpha"],
                                                 lora_dropout=recipe["lora_dropout"], bias="none",
                                                 task_type="CAUSAL_LM", target_modules=recipe["target_modules"]))
    return model, tok, "transformers+peft"


def attach_adapter(model, adapter_dir):
    from peft import PeftModel
    return PeftModel.from_pretrained(model, str(adapter_dir))


def ece(confidences, corrects, bins=10):
    if not confidences:
        return None
    total, err = len(confidences), 0.0
    for b in range(bins):
        lo, hi = b / bins, (b + 1) / bins
        idx = [i for i, c in enumerate(confidences) if (lo <= c < hi) or (b == bins - 1 and c == 1.0)]
        if not idx:
            continue
        acc = sum(corrects[i] for i in idx) / len(idx)
        conf = sum(confidences[i] for i in idx) / len(idx)
        err += abs(acc - conf) * len(idx) / total
    return err


def require_report(name, verdict_key="verdict", accepted=("PASS",)):
    p = OUT / name
    if not p.is_file():
        raise SystemExit(f"[gate] missing {p}; run the preceding step first")
    rep = read_json(p)
    if rep.get(verdict_key) not in accepted:
        raise SystemExit(f"[gate] {name} verdict {rep.get(verdict_key)} is not in {list(accepted)}; refusing to continue")
    return rep


def which(*names):
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    return None


def host_info():
    return {"host": platform.node() or "unknown-host", "platform": platform.platform(), "python": sys.version.split()[0]}
