"""Network-free adversarial contracts for source-bound, unexecuted wheel bytes."""
from __future__ import annotations

import base64
import csv
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import stat
import struct
import tempfile
import unittest
from unittest import mock
import warnings
import zipfile


TOOL = Path(__file__).resolve().parents[1] / "tools" / "verify_wheel_source.py"
SPEC = importlib.util.spec_from_file_location("oac_wheel_verification", TOOL)
assert SPEC is not None and SPEC.loader is not None
verification = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(verification)
REVISION = "1234567890abcdef1234567890abcdef12345678"
DIST = "szl_oac_clinical_gateway-2.5.1.dist-info"
FILENAME = "szl_oac_clinical_gateway-2.5.1-py3-none-any.whl"


def source_contract():
    source = {
        "owned_agent_clinical_control.py": ("clinical-gateway/src/owned_agent_clinical_control.py", b"# reviewed controller\n"),
        "oac_clinical_resources/__init__.py": ("clinical-gateway/src/oac_clinical_resources/__init__.py", b"# reviewed resources\n"),
        "oac_clinical_resources/assets/clinical-gateway/fixtures/assay_map.json": ("clinical-gateway/fixtures/assay_map.json", b"{}\n"),
        DIST + "/licenses/LICENSE": ("clinical-gateway/LICENSE", b"Apache license fixture\n"),
    }
    assets = [{"path": "clinical-gateway/fixtures/assay_map.json", "size_bytes": 3,
               "sha256": hashlib.sha256(b"{}\n").hexdigest()}]
    manifest = (json.dumps({"schema": "szl-oac/portable-workspace-assets/v1", "package_version": "2.5.1", "files": assets},
                           sort_keys=True, indent=2) + "\n").encode()
    generated = {
        "oac_clinical_resources/assets/manifest.json": manifest,
        "oac_clinical_resources/_asset_integrity.py": (
            '# Generated by the trusted build from canonical source assets.\n'
            f'MANIFEST_SHA256 = "{hashlib.sha256(manifest).hexdigest()}"\n').encode(),
    }
    return {"source_revision": REVISION, "name": "szl-oac-clinical-gateway", "version": "2.5.1",
            "requires_python": ">=3.11,<3.14", "description": "fixture gateway", "license": "Apache-2.0",
            "scripts": {"owned-agent-clinical-control": "owned_agent_clinical_control:main"},
            "top_levels": {"owned_agent_clinical_control", "oac_clinical_resources"},
            "dependencies": [("build", ("<2", ">=1.2"), "test"),
                             ("cryptography", ("<51", ">=46"), None)],
            "extras": ["test"],
            "dist_info": DIST, "wheel_filename": FILENAME, "source": source, "generated": generated}


def wheel_members():
    contract = source_contract()
    files = {name: payload for name, (_, payload) in contract["source"].items()}
    files.update(contract["generated"])
    files[DIST + "/METADATA"] = (
        "Metadata-Version: 2.4\nName: szl-oac-clinical-gateway\nVersion: 2.5.1\n"
        "Summary: fixture gateway\nRequires-Python: >=3.11,<3.14\nLicense-Expression: Apache-2.0\n"
        "License-File: LICENSE\nRequires-Dist: cryptography<51,>=46\nProvides-Extra: test\n"
        "Requires-Dist: build<2,>=1.2; extra == \"test\"\n\nGenerated description fixture\n").encode()
    files[DIST + "/WHEEL"] = b"Wheel-Version: 1.0\nGenerator: fixture\nRoot-Is-Purelib: true\nTag: py3-none-any\n"
    files[DIST + "/entry_points.txt"] = b"[console_scripts]\nowned-agent-clinical-control = owned_agent_clinical_control:main\n"
    files[DIST + "/top_level.txt"] = b"oac_clinical_resources\nowned_agent_clinical_control\n"
    return files


def make_wheel(files=None, *, rows=None, extra_entries=(), compression=zipfile.ZIP_DEFLATED):
    files = dict(wheel_members() if files is None else files)
    if rows is None:
        rows = [[name, "sha256=" + base64.urlsafe_b64encode(hashlib.sha256(raw).digest()).decode().rstrip("="), str(len(raw))]
                for name, raw in files.items()]
        rows.append([DIST + "/RECORD", "", ""])
    stream = io.StringIO(newline="")
    csv.writer(stream).writerows(rows)
    files[DIST + "/RECORD"] = stream.getvalue().encode()
    output = io.BytesIO()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        with zipfile.ZipFile(output, "w", compression=compression) as archive:
            for name, raw in files.items():
                archive.writestr(name, raw)
            for info, raw in extra_entries:
                archive.writestr(info, raw)
    return output.getvalue()


class WheelProofTests(unittest.TestCase):
    def verify(self, raw=None, *, filename=FILENAME):
        return verification.verify_wheel_bytes(make_wheel() if raw is None else raw, filename, source_contract())

    def test_matching_closed_wheel_proves_source_without_authority(self):
        receipt = self.verify()
        self.assertIs(receipt["complete"], True)
        self.assertEqual(REVISION, receipt["source_revision"])
        self.assertEqual(4, len(receipt["source_files"]))
        self.assertEqual(2, len(receipt["derived_files"]))
        self.assertEqual(10, receipt["record_hashed_members"])
        for field in ("clinical_use_authorized", "real_phi_authorized", "site_validated",
                      "production_promotion_allowed", "source_signature_verified", "wheel_executed"):
            self.assertIs(receipt[field], False, field)

    def test_valid_record_cannot_launder_modified_controller_assets_or_license(self):
        for name in source_contract()["source"]:
            files = wheel_members()
            files[name] += b"tampered"
            with self.subTest(name=name), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_derived_manifest_or_integrity_module_must_be_reconstructed(self):
        for name in source_contract()["generated"]:
            files = wheel_members()
            files[name] += b"tampered"
            with self.subTest(name=name), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_generated_integrity_text_allows_only_consistent_platform_newlines(self):
        name = "oac_clinical_resources/_asset_integrity.py"
        files = wheel_members()
        files[name] = files[name].replace(b"\n", b"\r\n")
        self.assertIs(self.verify(make_wheel(files))["complete"], True)
        files[name] = files[name].replace(b"\r\n", b"\n", 1)
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(files))

    def test_missing_or_extra_members_fail_even_with_consistent_record(self):
        files = wheel_members()
        del files["owned_agent_clinical_control.py"]
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(files))
        for name in ("surprise.py", DIST + "/surprise.txt", DIST + "/RECORD.jws"):
            files = dict(wheel_members(), **{name: b"surprise"})
            with self.subTest(name=name), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_duplicate_archive_entry_is_not_collapsed(self):
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(extra_entries=[("owned_agent_clinical_control.py", b"duplicate")]))

    def test_unsafe_paths_and_windows_case_aliases_fail(self):
        for name in ("../escape.py", "/escape.py", "a/../escape.py", "a//b.py", "a\\b.py", "C:escape.py",
                     "a/CON", "a/trailing.", "a/trailing ", "OWNED_AGENT_CLINICAL_CONTROL.PY", "a/\x01.py"):
            with self.subTest(name=name), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(extra_entries=[(name, b"unsafe")]))

    def test_directory_symlink_and_special_entries_fail(self):
        for mode, name in ((stat.S_IFDIR | 0o755, "directory/"), (stat.S_IFLNK | 0o777, "link.py"),
                           (stat.S_IFIFO | 0o600, "fifo.py")):
            info = zipfile.ZipInfo(name)
            info.create_system = 3
            info.external_attr = mode << 16
            with self.subTest(mode=mode), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(extra_entries=[(info, b"target")]))

    def test_encrypted_flag_rejected_without_reading_payload(self):
        raw = bytearray(make_wheel())
        position = raw.index(b"PK\x01\x02")
        flags = struct.unpack_from("<H", raw, position + 8)[0]
        struct.pack_into("<H", raw, position + 8, flags | 1)
        with self.assertRaises(verification.VerificationError):
            self.verify(bytes(raw))

    def test_declared_and_actual_size_limits_and_compression_bomb_fail(self):
        for constant, limit in (("MAX_WHEEL_BYTES", 32), ("MAX_MEMBER_BYTES", 8), ("MAX_TOTAL_BYTES", 64), ("MAX_MEMBERS", 2)):
            with self.subTest(constant=constant), mock.patch.object(verification, constant, limit):
                with self.assertRaises(verification.VerificationError):
                    self.verify()
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(extra_entries=[("bomb.py", b"0" * 100_000)]))

    def test_unsupported_compression_and_invalid_zip_fail(self):
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(compression=zipfile.ZIP_BZIP2))
        for raw in (b"", b"not zip", make_wheel()[:-30]):
            with self.subTest(length=len(raw)), self.assertRaises(verification.VerificationError):
                self.verify(raw)

    def test_record_duplicate_missing_extra_or_malformed_rows_fail(self):
        files = wheel_members()
        rows = [[name, "sha256=" + base64.urlsafe_b64encode(hashlib.sha256(raw).digest()).decode().rstrip("="), str(len(raw))]
                for name, raw in files.items()] + [[DIST + "/RECORD", "", ""]]
        for bad in (rows + [rows[0]], rows[1:], rows + [["extra.py", "sha256=wrong", "5"]],
                    [["too", "few"]], [["too", "many", "values", "here"]], [["../escape", "", ""]]):
            with self.subTest(rows=bad[-1]), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files, rows=bad))

    def test_record_hash_size_self_hash_and_noncanonical_encodings_fail(self):
        files = wheel_members()
        good = [[name, "sha256=" + base64.urlsafe_b64encode(hashlib.sha256(raw).digest()).decode().rstrip("="), str(len(raw))]
                for name, raw in files.items()] + [[DIST + "/RECORD", "", ""]]
        for index, field, value in ((0, 1, ""), (0, 1, "md5=AAAA"), (0, 1, "sha256=AAAA"),
                                    (0, 1, good[0][1] + "="), (0, 2, "-1"), (0, 2, "01"),
                                    (0, 2, "1.0"), (0, 2, "999"), (-1, 1, "sha256=AAAA"), (-1, 2, "0")):
            rows = [row[:] for row in good]
            rows[index][field] = value
            with self.subTest(value=value), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files, rows=rows))

    def test_generated_metadata_identity_and_duplicate_headers_fail(self):
        for suffix, old, new in (("METADATA", b"Version: 2.5.1", b"Version: 9.0"),
                                 ("METADATA", b"Name: szl-oac-clinical-gateway", b"Name: attacker"),
                                 ("METADATA", b"Version: 2.5.1", b"Version: 2.5.1\nVersion: 2.5.1"),
                                 ("WHEEL", b"Root-Is-Purelib: true", b"Root-Is-Purelib: false"),
                                 ("WHEEL", b"Tag: py3-none-any", b"Tag: cp312-cp312-win_amd64"),
                                 ("entry_points.txt", b"owned_agent_clinical_control:main", b"attacker:main"),
                                 ("top_level.txt", b"owned_agent_clinical_control", b"attacker")):
            files = wheel_members()
            files[DIST + "/" + suffix] = files[DIST + "/" + suffix].replace(old, new)
            with self.subTest(suffix=suffix, new=new), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_encoded_metadata_headers_cannot_launder_raw_identity_or_dependencies(self):
        changes = (
            (b"Name: szl-oac-clinical-gateway", b"Name: =?utf-8?q?szl-oac-clinical-gateway?="),
            (b"Requires-Dist: cryptography<51,>=46",
             b"Requires-Dist: =?utf-8?q?cryptography=3C51=2C=3E=3D46?="),
        )
        for old, new in changes:
            files = wheel_members()
            metadata = DIST + "/METADATA"
            self.assertIn(old, files[metadata])
            files[metadata] = files[metadata].replace(old, new, 1)
            with self.subTest(old=old), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_requires_python_bound_order_is_normalized_without_weakening(self):
        files = wheel_members()
        metadata = DIST + "/METADATA"
        files[metadata] = files[metadata].replace(
            b"Requires-Python: >=3.11,<3.14", b"Requires-Python: <3.14,>=3.11", 1)
        self.assertIs(self.verify(make_wheel(files))["complete"], True)
        for weakened in (b">=3.11", b">=3.10,<3.14", b">=3.11,<3.15"):
            changed = wheel_members()
            changed[metadata] = changed[metadata].replace(b"Requires-Python: >=3.11,<3.14",
                                                           b"Requires-Python: " + weakened, 1)
            with self.subTest(weakened=weakened), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(changed))

    def test_rehashed_wheel_cannot_add_install_dependency(self):
        files = wheel_members()
        metadata = DIST + "/METADATA"
        files[metadata] = files[metadata].replace(
            b"\n\nGenerated description fixture\n",
            b"\nRequires-Dist: unexpected-install-dependency\n\nGenerated description fixture\n",
            1,
        )
        with self.assertRaises(verification.VerificationError):
            self.verify(make_wheel(files))

    def test_rehashed_wheel_cannot_change_declared_dependencies_or_extras(self):
        changes = (
            (b"cryptography<51,>=46", b"cryptography<50,>=46"),
            (b"cryptography<51,>=46", b"other-package<51,>=46"),
            (b"Requires-Dist: cryptography<51,>=46\n", b""),
            (b"Requires-Dist: build<2,>=1.2; extra == \"test\"\n", b""),
            (b"build<2,>=1.2; extra == \"test\"", b"build<2,>=1.2"),
            (b"build<2,>=1.2; extra == \"test\"", b"build<2,>=1.2; extra == \"other\""),
            (b"Provides-Extra: test\n", b""),
            (b"Provides-Extra: test\n", b"Provides-Extra: test\nProvides-Extra: other\n"),
            (b"Provides-Extra: test\n", b"Provides-Extra: test\nProvides-Extra: test\n"),
            (b"Requires-Dist: cryptography<51,>=46\n",
             b"Requires-Dist: cryptography<51,>=46\nRequires-Dist: cryptography<51,>=46\n"),
        )
        for old, new in changes:
            files = wheel_members()
            metadata = DIST + "/METADATA"
            self.assertIn(old, files[metadata])
            files[metadata] = files[metadata].replace(old, new, 1)
            with self.subTest(old=old, new=new), self.assertRaises(verification.VerificationError):
                self.verify(make_wheel(files))

    def test_dependency_profile_rejects_unhandled_source_syntax(self):
        for invalid in ("build[wheel]>=1.2", "build @ https://example.invalid/pkg.whl",
                        "build>=1.2; python_version < '3.14'", "build>=1.2,<2,<2", "build~=1.2"):
            with self.subTest(invalid=invalid), self.assertRaises(verification.VerificationError):
                verification.declared_dependencies({"dependencies": [invalid]})
        with self.assertRaises(verification.VerificationError):
            verification.declared_dependencies({"optional-dependencies": {"Test_Extra": ["build>=1.2"]}})

    def test_filename_identity_must_match_declared_source(self):
        for filename in ("wrong.whl", FILENAME.replace("2.5.1", "2.5.2"), "../" + FILENAME):
            with self.subTest(filename=filename), self.assertRaises(verification.VerificationError):
                self.verify(filename=filename)


class SourceAndCliTests(unittest.TestCase):
    def test_mutable_partial_uppercase_nonstring_revisions_fail(self):
        for revision in ("HEAD", "main", REVISION[:8], REVISION.upper(), REVISION + "\n", None, True):
            with self.subTest(revision=revision), self.assertRaises(verification.VerificationError):
                verification.require_revision(revision)

    def test_git_command_disables_replacements_and_inherited_git_redirection(self):
        with mock.patch.object(verification, "bounded_command", return_value=b"commit\n") as command:
            with mock.patch.dict("os.environ", {"GIT_DIR": "hostile", "GIT_REPLACE_REF_BASE": "hostile"}):
                verification.git_read(Path("fixture"), "cat-file", "-t", REVISION)
        argv = command.call_args.args[0]
        self.assertIn("--no-replace-objects", argv)
        self.assertNotIn("GIT_DIR", command.call_args.kwargs["env"])
        self.assertNotIn("GIT_REPLACE_REF_BASE", command.call_args.kwargs["env"])

    def test_actual_immutable_manifest_closes_all_modules_and_assets(self):
        repo = Path(__file__).resolve().parents[2]
        revision = verification.git_read(repo, "rev-parse", "HEAD").decode().strip()
        contract = verification.manifest_from_git(repo, revision)
        self.assertEqual(17, len(contract["source"]))
        self.assertEqual(2, len(contract["generated"]))
        self.assertIn("oac_clinical_resources/__main__.py", contract["source"])
        self.assertIn("oac_live_transport_bridge.py", contract["source"])
        self.assertIn(DIST + "/licenses/LICENSE", contract["source"])
        self.assertEqual([("build", ("<2", ">=1.2"), "test"),
                          ("cryptography", ("<51", ">=46"), None)], contract["dependencies"])
        self.assertEqual(["test"], contract["extras"])

    def test_cli_retains_sanitized_failure_receipt(self):
        with tempfile.TemporaryDirectory(prefix="oac-wheel-tests-") as temporary:
            output = Path(temporary) / "failure.json"
            with mock.patch.object(verification, "verify_wheel", side_effect=verification.VerificationError("WHEEL_SOURCE_MISMATCH")):
                with mock.patch("sys.stdout", io.StringIO()):
                    status = verification.main(["--wheel", "fixture.whl", "--git-revision", REVISION, "--output", str(output)])
            self.assertEqual(1, status)
            receipt = json.loads(output.read_bytes())
            self.assertIs(receipt["complete"], False)
            self.assertEqual("WHEEL_SOURCE_MISMATCH", receipt["failure_code"])
            self.assertIs(receipt["clinical_use_authorized"], False)

    def test_existing_receipt_is_never_overwritten(self):
        with tempfile.TemporaryDirectory(prefix="oac-wheel-tests-") as temporary:
            output = Path(temporary) / "existing.json"
            output.write_bytes(b"retained evidence")
            with mock.patch.object(verification, "verify_wheel", return_value={"complete": True}):
                with mock.patch("sys.stdout", io.StringIO()), mock.patch("sys.stderr", io.StringIO()):
                    status = verification.main(["--wheel", "fixture.whl", "--git-revision", REVISION, "--output", str(output)])
            self.assertEqual(2, status)
            self.assertEqual(b"retained evidence", output.read_bytes())

    def test_low_space_fails_without_reading_wheel_or_git(self):
        with mock.patch.object(verification.shutil, "disk_usage", return_value=mock.Mock(free=511 * 1024 * 1024)):
            with mock.patch.object(verification, "manifest_from_git") as manifest:
                with self.assertRaises(verification.VerificationError):
                    verification.verify_wheel(Path("unused.whl"), Path("unused"), REVISION)
                manifest.assert_not_called()


if __name__ == "__main__":
    unittest.main()
